[Books]
CATEGORIES = [  
    "Visual Art",
    "Literature",
    "History",
    "Music",
    "Architecture",
    "Artificial Intelligence in General",
    "Generative Artificial Intelligence",
    "Machine Learning",
    "Deep Learning",
    "Bayesian Statistics",
    "Causal Inference",
    "Biology in General",
    "Genetics",
    "Bioinformatics",
    "Mathematical Biology",
    "Blockchain",
    "Computer & Programming in General",
    "Cosmology, Quantum Mechanics",
    "Data Science & Statistics in General",
    "Medical Statistics",
    "Structural Equation Modeling",
    "Time Series Forecasting",
    "Big Data Analysis",
    "Engineering in General",
    "Futurology",
    "Science, General",
    "Physics in General",
    "Chemistry in General",
    "Internet of Things",
    "Language, Linguistics",
    "Mathematics in General",
    "Calculus",
    "Linear Algebra",
    "Geometry",
    "Topology",
    "Number Theory",
    "Mathematical Analysis",
    "Medicine in General",
    "Pain",
    "Nanotechnology",
    "Network Science",
    "Complex Systems",
    "Neuroscience",
    "Philosophy",
    "Psychiatry in General",
    "Psychopharmacology",
    "Psychotherapy, psychoanalysis",
    "Psychology",
    "Spirituality, Religion",
    "Quantum Computing",
    "Others"
]

[Articles]
CATEGORIES = [
    "Neuroscience and Brain Function",
    "Mental Health and Psychiatry",
    "Philosophy and Ethics of Science",
    "Artificial Intelligence and Machine Learning",
    "Psychological Theories and Behavioral Science",
    "Quantitative and Statistical Methods",
    "Evolution and Biology",
    "Chronic Diseases and Aging",
    "Interdisciplinary Approaches",
    "Emerging Technologies in Medicine",
    "Physics and Mathematics"
]